a:5:{i:0;s:100:"SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
";i:1;s:1543:"#0 G:\xampp\htdocs\magento1.9\lib\Zend\Db\Adapter\Pdo\Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect()
#1 G:\xampp\htdocs\magento1.9\lib\Varien\Db\Adapter\Pdo\Mysql.php(396): Zend_Db_Adapter_Pdo_Mysql->_connect()
#2 G:\xampp\htdocs\magento1.9\lib\Zend\Db\Adapter\Abstract.php(460): Varien_Db_Adapter_Pdo_Mysql->_connect()
#3 G:\xampp\htdocs\magento1.9\lib\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('SET NAMES utf8', Array)
#4 G:\xampp\htdocs\magento1.9\lib\Varien\Db\Adapter\Pdo\Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SET NAMES utf8', Array)
#5 G:\xampp\htdocs\magento1.9\app\code\core\Mage\Core\Model\Resource.php(179): Varien_Db_Adapter_Pdo_Mysql->query('SET NAMES utf8')
#6 G:\xampp\htdocs\magento1.9\app\code\core\Mage\Core\Model\Resource.php(110): Mage_Core_Model_Resource->_newConnection('pdo_mysql', Array)
#7 G:\xampp\htdocs\magento1.9\app\code\core\Mage\Core\Model\Resource\Setup.php(141): Mage_Core_Model_Resource->getConnection('core_setup')
#8 G:\xampp\htdocs\magento1.9\app\code\core\Mage\Core\Model\Resource\Setup.php(234): Mage_Core_Model_Resource_Setup->__construct('core_setup')
#9 G:\xampp\htdocs\magento1.9\app\code\core\Mage\Core\Model\App.php(428): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#10 G:\xampp\htdocs\magento1.9\app\code\core\Mage\Core\Model\App.php(354): Mage_Core_Model_App->_initModules()
#11 G:\xampp\htdocs\magento1.9\app\Mage.php(683): Mage_Core_Model_App->run(Array)
#12 G:\xampp\htdocs\magento1.9\index.php(83): Mage::run('', 'store')
#13 {main}";s:3:"url";s:12:"/magento1.9/";s:11:"script_name";s:21:"/magento1.9/index.php";s:4:"skin";s:7:"default";}